# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: myproto.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'myproto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmyproto.proto\x12\x07myproto\"\x0e\n\x0c\x45mptyRequest\"C\n\x0cSharedUpdate\x12\x0f\n\x07weights\x18\x01 \x01(\x0c\x12\r\n\x05round\x18\x02 \x01(\x05\x12\x13\n\x0bnum_samples\x18\x03 \x01(\x05\"0\n\x0eSharedResponse\x12\x0f\n\x07weights\x18\x01 \x01(\x0c\x12\r\n\x05round\x18\x02 \x01(\x05\",\n\x03\x41\x63k\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x15\n\rcurrent_round\x18\x02 \x01(\x05\x32\x89\x01\n\nAggregator\x12\x37\n\x10SendSharedUpdate\x12\x15.myproto.SharedUpdate\x1a\x0c.myproto.Ack\x12\x42\n\x10GetSharedWeights\x12\x15.myproto.EmptyRequest\x1a\x17.myproto.SharedResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myproto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTYREQUEST']._serialized_start=26
  _globals['_EMPTYREQUEST']._serialized_end=40
  _globals['_SHAREDUPDATE']._serialized_start=42
  _globals['_SHAREDUPDATE']._serialized_end=109
  _globals['_SHAREDRESPONSE']._serialized_start=111
  _globals['_SHAREDRESPONSE']._serialized_end=159
  _globals['_ACK']._serialized_start=161
  _globals['_ACK']._serialized_end=205
  _globals['_AGGREGATOR']._serialized_start=208
  _globals['_AGGREGATOR']._serialized_end=345
# @@protoc_insertion_point(module_scope)
