# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: myproto.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'myproto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmyproto.proto\x12\x06\x66\x65\x64\x61vg\"\x0e\n\x0c\x45mptyRequest\"C\n\x0cSharedUpdate\x12\x0f\n\x07weights\x18\x01 \x01(\x0c\x12\r\n\x05round\x18\x02 \x01(\x05\x12\x13\n\x0bnum_samples\x18\x03 \x01(\x05\"/\n\rSharedWeights\x12\x0f\n\x07weights\x18\x01 \x01(\x0c\x12\r\n\x05round\x18\x02 \x01(\x05\"\x11\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\x84\x01\n\nAggregator\x12\x35\n\x10SendSharedUpdate\x12\x14.fedavg.SharedUpdate\x1a\x0b.fedavg.Ack\x12?\n\x10GetSharedWeights\x12\x14.fedavg.EmptyRequest\x1a\x15.fedavg.SharedWeightsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myproto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTYREQUEST']._serialized_start=25
  _globals['_EMPTYREQUEST']._serialized_end=39
  _globals['_SHAREDUPDATE']._serialized_start=41
  _globals['_SHAREDUPDATE']._serialized_end=108
  _globals['_SHAREDWEIGHTS']._serialized_start=110
  _globals['_SHAREDWEIGHTS']._serialized_end=157
  _globals['_ACK']._serialized_start=159
  _globals['_ACK']._serialized_end=176
  _globals['_AGGREGATOR']._serialized_start=179
  _globals['_AGGREGATOR']._serialized_end=311
# @@protoc_insertion_point(module_scope)
